sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - node
before_script:
  - npm install --save-dev @types/jest
script:
  - cd ngx-google-translate-ui
  - npm install
  - npm run test-ci
  - npm run build-ci
