sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - node
before_script:
  - npm install -g @angular/cli
  - npm install --save-dev @types/jest
script:
  - cd ng-google-translate-ui
  - npm install
  - npm run test-ci
  - npm run build-ci
